// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chat-app-ui/Aurora.tsx": () => import("../components/mockups/chat-app-ui/Aurora.tsx"),
  "./components/mockups/chat-app-ui/Nebula.tsx": () => import("../components/mockups/chat-app-ui/Nebula.tsx"),
  "./components/mockups/chat-app-ui/Obsidian.tsx": () => import("../components/mockups/chat-app-ui/Obsidian.tsx")
};
